name: Sample Workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: An optional string workflow input
        type: string
      has_admin_role:
        description: An optional choice workflow input
        type: choice
        options:
          - "true"
          - "false"
        default: "false"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Run a script printing environment vars to stdout
        run: |
          node -e 'console.log(`::notice::NAME_INPUT: ${process.env.NAME_INPUT}`)'
          node -e 'console.log(`::notice::HAS_ADMIN_ROLE: ${process.env.HAS_ADMIN_ROLE}`)'
          node -e 'console.log(`::notice::GH_INPUT_CONTEXT: ${process.env.GH_INPUT_CONTEXT}`)'
        env:
          NAME_INPUT: ${{ inputs.name }}
          HAS_ADMIN_ROLE: ${{ inputs.has_admin_role }}
          GH_INPUT_CONTEXT: ${{ toJSON(github.event.inputs) }}
